# Generated by Django 5.0.2 on 2024-02-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('time_recevied', models.TimeField()),
                ('battery_voltage', models.FloatField(help_text='Battery voltage in volts')),
                ('is_charging', models.BooleanField(default=False, help_text='Indicates if the device is currently charging')),
                ('satellites_visible', models.PositiveIntegerField(help_text='Number of visible GNSS satellites')),
                ('cellid', models.IntegerField(help_text='ID of the current LTE cell station')),
                ('ac', models.CharField(help_text='Tracking Area Code of LTE', max_length=100)),
                ('rsrp', models.FloatField(help_text='Reference Signal Received Power of LTE in dBm')),
                ('rsrq', models.FloatField(help_text='Reference Signal Received Quality of LTE in dB')),
                ('snr', models.FloatField(help_text='Signal to Noise Ratio of LTE in dB')),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_recevied', models.TimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('geo_altitude', models.FloatField()),
                ('height', models.FloatField()),
                ('velocity_x', models.FloatField(help_text='X-component velocity in m/s')),
                ('velocity_y', models.FloatField(help_text='Y-component velocity in m/s')),
                ('velocity_z', models.FloatField(help_text='Z-component velocity in m/s')),
                ('horizontal_accuracy', models.FloatField()),
                ('vertical_accuracy', models.FloatField()),
                ('speed_accuracy', models.FloatField()),
                ('pressure', models.FloatField()),
            ],
        ),
    ]
