# Generated by Django 5.0.2 on 2024-02-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronetag', '0003_telemetrymessage_flight_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmessage',
            name='cellid',
            field=models.CharField(help_text='ID of the current LTE cell station', max_length=200),
        ),
    ]
