# Generated by Django 5.0.2 on 2024-02-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronetag', '0004_alter_statusmessage_cellid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusmessage',
            old_name='battery_voltage',
            new_name='battery',
        ),
        migrations.RenameField(
            model_name='statusmessage',
            old_name='is_charging',
            new_name='charging',
        ),
        migrations.RenameField(
            model_name='statusmessage',
            old_name='satellites_visible',
            new_name='satellites',
        ),
        migrations.RenameField(
            model_name='statusmessage',
            old_name='ac',
            new_name='tac',
        ),
        migrations.RemoveField(
            model_name='telemetrymessage',
            name='flight_id',
        ),
        migrations.AddField(
            model_name='statusmessage',
            name='s_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='telemetrymessage',
            name='t_id',
            field=models.IntegerField(null=True),
        ),
    ]
