# Generated by Django 5.0.2 on 2024-02-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronetag', '0005_rename_battery_voltage_statusmessage_battery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrymessage',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='statusmessage',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='statusmessage',
            name='time_recevied',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='telemetrymessage',
            name='time_recevied',
            field=models.TimeField(null=True),
        ),
    ]
