# Generated by Django 5.0.2 on 2024-02-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronetag', '0007_alter_statusmessage_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmessage',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='statusmessage',
            name='time_recevied',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='telemetrymessage',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='telemetrymessage',
            name='time_recevied',
            field=models.DateTimeField(null=True),
        ),
    ]
