# Generated by Django 5.0.2 on 2024-02-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronetag', '0008_alter_statusmessage_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmessage',
            name='battery',
            field=models.DecimalField(decimal_places=2, help_text='Battery voltage in volts', max_digits=5),
        ),
    ]
